# Generated by Django 4.0.4 on 2022-05-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avirtual', '0003_alter_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='capitulos'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='video',
            field=models.FileField(blank=True, upload_to='capitulos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cursos'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='lecciones'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='video',
            field=models.FileField(blank=True, upload_to='lecciones'),
        ),
    ]
