# Generated by Django 4.0.4 on 2022-05-28 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avirtual', '0005_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avirtual.curso')),
            ],
            options={
                'ordering': ['-inscripcion'],
            },
        ),
    ]
