# Generated by Django 4.0.4 on 2022-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avirtual', '0007_miscursos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miscursos',
            name='curso',
        ),
        migrations.AddField(
            model_name='miscursos',
            name='curso',
            field=models.ManyToManyField(null=True, to='avirtual.curso'),
        ),
    ]
