# Generated by Django 4.0.4 on 2022-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avirtual', '0008_remove_miscursos_curso_miscursos_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscursos',
            name='curso',
            field=models.ManyToManyField(to='avirtual.curso'),
        ),
    ]
